            - name: Flutter Build
  # You may pin to the exact commit or the version.
  # uses: AcmeSoftwareLLC/flutter-build@848d1196b5e814d2c368711dde8365295d736937
  uses: AcmeSoftwareLLC/flutter-build@v1.0.2
  with:
    # Platform
    platform: 
    # Build Name
    build-name: # optional
    # Build Number
    build-number: # optional
    # Base Href
    base-href: # optional
    # Dart Define File
    dart-define-file: # optional
    # Working Directory
    working-directory: # optional, default is .
    # Run Pub Get
    pub-get: # optional, default is false
    # Allows you to run a script at the start of the build
    pre: # optional
    # Tree Shake Icons
    tree-shake-icons: # optional, default is true
          
